plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.2.2.cjs

# styled-component issue (https://github.com/styled-components/styled-components/issues/3082)
packageExtensions:
  styled-components@*:
    dependencies:
      babel-plugin-macros: '*'
      react-is: '*'
